import { BrawlStarsClient } from "../../src";
import { singleton } from "./index";

// I don't care about the API key since you can't do anything with it
const token =
	"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjAwMGU1ZGI5LWYxMmYtNDU5ZS05NGQ0LWQxYjI0ODVkZjY5MiIsImlhdCI6MTcwMDYwNzkwNiwic3ViIjoiZGV2ZWxvcGVyLzYzYTI2NjI5LWRlMGUtYjM0Zi0zNjUxLTMzMTY4ZDM1N2ZhZSIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiNDAuNzYuMjM4LjIxMCIsIjAuMC4wLjAiLCIxNzMuNzYuMTIyLjIxOSIsIjEwOC4yNi4yMzguMTU1IiwiNDUuNzkuMjE4Ljc5Il0sInR5cGUiOiJjbGllbnQifV19.jZ6JwsuSylKu0UgrUNqdEmB192HDCPzBPKejxrmj4HUUCBRNjVdvhcFrDkMpZ0KFd9RaTtuTwz7z8Wr5Jq3qiw";
export const client = singleton("brawlStarsClient", new BrawlStarsClient(token));
