name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Install Dependencies
        run: yarn
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
        with:
          cache-prefix: brawltracker_
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn vitest run
      # - name: Build, test, and lint
      #   run: yarn ci
      - name: "Report Coverage"
        if: always() # Also generate the report if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
