name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Install Dependencies
        run: yarn
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5
        with:
          cache-prefix: turbogha_ # Custom prefix for cache keys
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      # - name: Build, test, and lint
      #   run: yarn ci
      # - name: "Report Coverage"
      #   if: always() # Also generate the report if tests are failing
      #   uses: davelosert/vitest-coverage-report-action@v2
